version: "3.8"
services:
#    api:
#        build:
#            dockerfile: Dockerfile
#            context: .
#        depends_on:
#            - postgres
#        environment:
#            DATABASE_URL: postgres://user:password@postgres:5432/db
#        ports:
#            - "8080:3000"
#        volumes:
#            - .:/zespolowka/src/app
#            - ./zespolowka/src/app/node_modules
#        command: npm run start:debug

    postgres:
        image: postgres:10.4
        environment: 
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: db
        ports:
          - "35000:5432"